### ISSUE TITLE
rmarkdown regression on citation_package

### ISSUE THREAD

**Issue by coatless** [coatless/uiucthemes#21]
E-mail from @noejn2:

> Every time I tried to compile my slides with either Rstudio or VS code, an error shows up: citation_package = “none” was deprecated. I tried playing around with the yaml part of the document, but came across an stranger issue. In short, my file will never compile when I try to include a bibliography and some citations

**Comment by noejn2** [comment]
@coatless : The problem has been solved. Something I forgot mentioning in my last email. For those who do not know. You must include `citation_package: natbib` in the following way:

```yaml
output: 
    uiucthemes::beamer_illinois:
        citation_package: natbib
```

That worked for me.
